.PHONY : theslides

theslides : week_1.slides.html week_2.slides.html week_3.slides.html week_4.slides.html week_5.slides.html week_6.slides.html week_7.slides.html week_8.slides.html t-sne.slides.html week_9.slides.html week_10.slides.html review.slides.html  

include ../Makefile

